import 'server-only';

import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { createServerRunner } from '@aws-amplify/adapter-nextjs';
import { generateServerClientUsingReqRes, type ClientUsingSSRReq } from '@aws-amplify/adapter-nextjs/data';
import type { AmplifyContext } from 'aws-amplify';
import type { Schema } from '@amplify/data/resource';

export type AmplifyOutputs = Parameters<typeof createServerRunner>[0]['config'];

/**
 * amplify_outputs.json is generated by `ampx sandbox` / `ampx pipeline-deploy`
 * and is not committed. It is read at runtime so that local development and
 * builds keep working (with the static config) when it does not exist yet.
 */
export async function readAmplifyOutputs(): Promise<Record<string, unknown> | null> {
  try {
    const raw = await readFile(path.join(process.cwd(), 'amplify_outputs.json'), 'utf8');
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    // Fallback: the copy embedded at build time (see next.config.ts).
    const embedded = process.env.AMPLIFY_OUTPUTS_JSON;
    if (!embedded) return null;
    try {
      return JSON.parse(embedded) as Record<string, unknown>;
    } catch {
      return null;
    }
  }
}

/**
 * Logs a failure for CloudWatch without leaking anything sensitive: only the
 * error name and a shortened single-line message — never the error object,
 * request metadata, credentials, tokens or configuration.
 */
export function logServerError(label: string, error: unknown): void {
  const name = error instanceof Error ? error.name : typeof error;
  const message = error instanceof Error ? error.message : '';
  const safeMessage = message.replace(/\s+/g, ' ').slice(0, 300);
  console.error(`[amplify] ${label} failed: ${name}${safeMessage ? `: ${safeMessage}` : ''}`);
}

export type AmplifyBackend = {
  runWithAmplifyServerContext: ReturnType<typeof createServerRunner>['runWithAmplifyServerContext'];
  client: ClientUsingSSRReq<Schema>;
};

function createBackend(json: Record<string, unknown>): AmplifyBackend {
  const config = json as AmplifyOutputs;
  const { runWithAmplifyServerContext } = createServerRunner({ config });
  const client = generateServerClientUsingReqRes<Schema>({ config });
  return { runWithAmplifyServerContext, client };
}

// Only a successfully created backend is kept for the life of the instance. A
// missing config or a failed setup is retried on the next request.
let backend: AmplifyBackend | undefined;
let pending: Promise<AmplifyBackend | null> | undefined;
let reportedMissingConfig = false;

function getBackend(): Promise<AmplifyBackend | null> {
  if (backend) return Promise.resolve(backend);
  pending ??= (async () => {
    try {
      const outputs = await readAmplifyOutputs();
      if (!outputs) {
        if (!reportedMissingConfig) {
          reportedMissingConfig = true;
          console.error('[amplify] amplify_outputs.json not found (file or build-time copy); using static content');
        }
        return null;
      }
      backend = createBackend(outputs);
      return backend;
    } catch (error) {
      logServerError('backend setup', error);
      return null;
    } finally {
      pending = undefined;
    }
  })();
  return pending;
}

const TIMEOUT_MS = 8000;

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(`Amplify request timed out after ${ms}ms`)), ms);
    promise.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      (error: unknown) => {
        clearTimeout(timer);
        reject(error);
      },
    );
  });
}

/**
 * Runs an operation as an anonymous visitor (identity pool guest role, no
 * cookies). Returns null when the backend is not configured or the call fails
 * (logged safely), letting callers fall back to static data.
 */
export async function runAsGuest<T>(
  operation: (backend: AmplifyBackend, context: AmplifyContext) => Promise<T>,
  label = 'guest request',
): Promise<T | null> {
  const resolved = await getBackend();
  if (!resolved) return null;
  try {
    return await withTimeout(
      resolved.runWithAmplifyServerContext({
        nextServerContext: null,
        operation: (context) => operation(resolved, context),
      }),
      TIMEOUT_MS,
    );
  } catch (error) {
    logServerError(label, error);
    return null;
  }
}
