import 'server-only';

import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { createServerRunner } from '@aws-amplify/adapter-nextjs';
import { generateServerClientUsingReqRes, type ClientUsingSSRReq } from '@aws-amplify/adapter-nextjs/data';
import type { AmplifyContext } from 'aws-amplify';
import type { Schema } from '@amplify/data/resource';

export type AmplifyOutputs = Parameters<typeof createServerRunner>[0]['config'];

/**
 * amplify_outputs.json is generated by `ampx sandbox` / `ampx pipeline-deploy`
 * and is not committed. It is read at runtime so that local development and
 * builds keep working (with the static config) when it does not exist yet.
 */
export async function readAmplifyOutputs(): Promise<Record<string, unknown> | null> {
  try {
    const raw = await readFile(path.join(process.cwd(), 'amplify_outputs.json'), 'utf8');
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    // Fallback: the copy embedded at build time (see next.config.ts).
    const embedded = process.env.AMPLIFY_OUTPUTS_JSON;
    if (!embedded) return null;
    try {
      return JSON.parse(embedded) as Record<string, unknown>;
    } catch {
      return null;
    }
  }
}

export type AmplifyBackend = {
  runWithAmplifyServerContext: ReturnType<typeof createServerRunner>['runWithAmplifyServerContext'];
  client: ClientUsingSSRReq<Schema>;
};

function createBackend(json: Record<string, unknown>): AmplifyBackend {
  const config = json as AmplifyOutputs;
  const { runWithAmplifyServerContext } = createServerRunner({ config });
  const client = generateServerClientUsingReqRes<Schema>({ config });
  return { runWithAmplifyServerContext, client };
}

let backend: Promise<AmplifyBackend | null> | undefined;

function getBackend(): Promise<AmplifyBackend | null> {
  backend ??= readAmplifyOutputs()
    .then((outputs) => (outputs ? createBackend(outputs) : null))
    .catch(() => null);
  return backend;
}

const TIMEOUT_MS = 8000;

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(`Amplify request timed out after ${ms}ms`)), ms);
    promise.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      (error: unknown) => {
        clearTimeout(timer);
        reject(error);
      },
    );
  });
}

/**
 * Runs an operation as an anonymous visitor (identity pool guest role, no
 * cookies), so pages stay statically renderable. Returns null when the backend
 * is not configured or the call fails, letting callers fall back to static data.
 */
export async function runAsGuest<T>(
  operation: (backend: AmplifyBackend, context: AmplifyContext) => Promise<T>,
): Promise<T | null> {
  const resolved = await getBackend();
  if (!resolved) return null;
  try {
    return await withTimeout(
      resolved.runWithAmplifyServerContext({
        nextServerContext: null,
        operation: (context) => operation(resolved, context),
      }),
      TIMEOUT_MS,
    );
  } catch (error) {
    console.error('[amplify] request failed, using static content instead:', error);
    return null;
  }
}
