/** Arabic strings for the Amplify Authenticator (it ships no Arabic dictionary). */
export const authVocabularyAr: Record<string, string> = {
  'Sign In': 'تسجيل الدخول',
  'Sign in': 'تسجيل الدخول',
  'Signing in': 'جارٍ تسجيل الدخول',
  'Sign in to your account': 'تسجيل الدخول إلى الحساب',
  Email: 'البريد الإلكتروني',
  'Enter your Email': 'البريد الإلكتروني',
  'Enter your email': 'البريد الإلكتروني',
  Username: 'البريد الإلكتروني',
  'Enter your username': 'البريد الإلكتروني',
  Password: 'كلمة المرور',
  'Enter your Password': 'كلمة المرور',
  'Enter your password': 'كلمة المرور',
  'Show password': 'إظهار كلمة المرور',
  'Hide password': 'إخفاء كلمة المرور',
  'Forgot your password?': 'نسيت كلمة المرور؟',
  'Forgot password?': 'نسيت كلمة المرور؟',
  'Reset your password': 'إعادة تعيين كلمة المرور',
  'Reset your Password': 'إعادة تعيين كلمة المرور',
  'Send code': 'إرسال الرمز',
  'Send Code': 'إرسال الرمز',
  Sending: 'جارٍ الإرسال',
  'Back to Sign In': 'العودة إلى تسجيل الدخول',
  Code: 'الرمز',
  'Confirmation Code': 'رمز التأكيد',
  'Enter your code': 'الرمز',
  'Enter your Confirmation Code': 'رمز التأكيد',
  'Resend Code': 'إعادة إرسال الرمز',
  'New password': 'كلمة المرور الجديدة',
  'New Password': 'كلمة المرور الجديدة',
  'Confirm Password': 'تأكيد كلمة المرور',
  'Please confirm your Password': 'تأكيد كلمة المرور',
  'Change Password': 'تغيير كلمة المرور',
  Changing: 'جارٍ التغيير',
  Submit: 'إرسال',
  Submitting: 'جارٍ الإرسال',
  Confirm: 'تأكيد',
  Confirming: 'جارٍ التأكيد',
  Skip: 'تخطي',
  Verify: 'التحقق',
  'Verify Contact': 'التحقق من وسيلة التواصل',
  'Account recovery requires verified contact information':
    'تتطلب استعادة الحساب التحقق من وسيلة التواصل',
  'We Emailed You': 'أرسلنا رسالة إلى بريدك',
  'It may take a minute to arrive': 'قد يستغرق وصولها دقيقة',
  'Your code is on the way. To log in, enter the code we emailed to':
    'الرمز في الطريق. لتسجيل الدخول يُرجى إدخال الرمز المرسل إلى',
  'Dismiss alert': 'إغلاق التنبيه',
  Loading: 'جارٍ التحميل',
  // Cognito error messages
  'Incorrect username or password.': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
  'User does not exist.': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
  'Password attempts exceeded': 'تجاوزت عدد المحاولات المسموح به. يُرجى المحاولة لاحقًا.',
  'Attempt limit exceeded, please try after some time.': 'تجاوزت عدد المحاولات المسموح به. يُرجى المحاولة لاحقًا.',
  'Invalid verification code provided, please try again.': 'رمز التحقق غير صحيح، يُرجى المحاولة مرة أخرى.',
  'Your passwords must match': 'كلمتا المرور غير متطابقتين',
  'Password must have at least 8 characters': 'يجب ألا تقل كلمة المرور عن 8 أحرف',
  'Password must have upper case letters': 'يجب أن تحتوي كلمة المرور على حرف إنجليزي كبير',
  'Password must have lower case letters': 'يجب أن تحتوي كلمة المرور على حرف إنجليزي صغير',
  'Password must have numbers': 'يجب أن تحتوي كلمة المرور على رقم',
  'Password must have special characters': 'يجب أن تحتوي كلمة المرور على رمز خاص',
};
